before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/termcord/main.go
    binary: termcord
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
    goarch:
      - 386
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Macos
      linux: Linux
      freebsd: FreeBSD
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
